export enum EProduct {
  diary = "dairy",
  pastries = "pastries",
  oils = "oils",
  sauces = "sauces",
  grains = "grains",
  vegetables = "vegetables",
  fruits = "fruits and berries",
  dried = "dried fruits",
  beans = "beans",
  moshrooms = "mushrooms",
  meat = "meat",
  sausages = "sausages",
  smoked = "smoked meat",
  fish = "fish and seafood",
  nuts = "nuts",
  sweets = "sweets",
  pasta = "pasta",
  soup = "soup",
  satad = "salad",
}
